name: Deploy Versiculando

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v3

      - name: Deploy no servidor
        uses: appleboy/ssh-action@v1.0.3
        env:
          SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: SUPABASE_URL,SUPABASE_KEY
          script: |
            cd /var/www/versiculando-main
            git checkout -- .env
            git pull origin main
            echo "VITE_SUPABASE_URL=$SUPABASE_URL" > .env
            echo "VITE_SUPABASE_ANON_KEY=$SUPABASE_KEY" >> .env
            echo "NODE_ENV=production" >> .env
            npm ci
            npm run build
            pm2 restart versiculando --update-env
            pm2 save
